core:
    site:
        name: "Murph"
        logo: "build/images/core/logo.svg"
        # controllers:
        #     - {name: 'Foo', action: 'App\Controller\ExampleController::foo'}
        pages:
            App\Entity\Page\SimplePage:
                name: 'Page simple'
                templates:
                    - {name: "Template 1", file: "page/simple/page.html.twig"}
