core:
    site:
        name: "Murph"
        logo: "build/images/core/logo.svg"
        # controllers:
        #     - {name: 'Foo', action: 'App\Controller\ExampleController::foo'}
        pages:
            App\Entity\Page\SimplePage:
                name: 'Simple page'
                templates:
                    - {name: "Default", file: "page/simple/default.html.twig"}
        # security:
        #     roles:
        #         - {name: 'Role foo', role: 'ROLE_FOO'}
        #         - {name: 'Role bar', role: 'ROLE_BAR'}
    file_manager:
        # mimes:
        #     - image/png
        #     - image/jpg
        #     - image/jpeg
        #     - image/gif
        #     - image/svg+xml
        #     - video/mp4
        #     - audio/mpeg3
        #     - audio/x-mpeg-3
        #     - multipart/x-zip
        #     - multipart/x-gzip
        #     - application/pdf
        #     - application/ogg
        #     - application/zip
        #     - application/rar
        #     - application/x-rar-compressed
        #     - application/x-zip-compressed
        #     - application/tar
        #     - application/x-tar
        #     - application/x-bzip
        #     - application/x-bzip2
        #     - application/x-gzip
        #     - application/octet-stream
        #     - application/msword
        #     - text/plain
        #     - text/css
        # path: "%kernel.project_dir%/public/uploads"
        # path_uri: "/uploads"
        # path_locked:
        #     - "%kernel.project_dir%/public/uploads"
