# See the configuration reference at https://github.com/scheb/2fa/blob/master/doc/configuration.md
scheb_two_factor:
    google:
        enabled: true
        issuer: "Murph"
        server_name:
        digits: 6
        leeway: 1
        template: "@Core/auth/2fa.html.twig"
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
