twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['@Core/form/bootstrap_4_form_theme.html.twig']
    paths:
        '%kernel.project_dir%/templates/core/': Core
        '%kernel.project_dir%/vendor/murph/murph-core/src/core/Resources/views/': Core

when@test:
    twig:
        strict_variables: true
