controllers:
    resource: ../../src/Controller/
    type: annotation

core_controllers:
    resource: ../../vendor/murph/murph-core/src/core/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
